apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregation-cronjob
spec:
  schedule: "20 14 * * *" # Runs daily at 10 AM; adjust as needed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregation-cronjob
            image: shaliniabeygunawardana/aggregation-cronjob:1.0.4
            ports:
            - containerPort: 8002
            imagePullPolicy: IfNotPresent
            env:
              - name: DB_STRING
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: db_string
              # Add other environment variables as needed
              - name: DB_USERNAME
                value: "admin"
              - name: DB_PASSWORD
                value: "Sha1014*"
              - name: DB_ENDPOINT
                value: "moon-agent-database.cu76c40m8t8k.us-east-1.rds.amazonaws.com"
              - name: DB_NAME
                value: "moon_agent"
              - name: REDSHIFT_DB_USERNAME
                value: "admin"
              - name: REDSHIFT_DB_PASSWORD
                value: "Sha1014*"
              - name: REDSHIFT_DB_ENDPOINT
                value: "default-workgroup.381492058808.us-east-1.redshift-serverless.amazonaws.com"
              - name: REDSHIFT_DB_NAME
                value: "dev"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-credentials
                    key: AWS_SECRET_ACCESS_KEY
              
          restartPolicy: OnFailure