
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  labels:
    app: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: shaliniabeygunawardana/agent-service:1.0.2
        ports:
        - containerPort: 8000
        env:
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "Sha1014*"
        - name: DB_ENDPOINT
          value: "moon-agent-database.cu76c40m8t8k.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "moon_agent"