apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  labels:
    app: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: shaliniabeygunawardana/agent-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "example"
        - name: DB_ENDPOINT
          value: "host.minikube.internal"
        - name: DB_NAME
          value: "moon_agent"