apiVersion: v1
kind: Service
metadata:
  name: fastapi-agent-service
spec:
  selector:
    app: fastapi-agent-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort