name: Build Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag (e.g., v1.0.0, feature-branch, etc.)"
        required: true
        default: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: agent
          file: agent/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-service:${{ github.event.inputs.image_tag }}
            ${{ secrets.DOCKER_USERNAME }}/my-service:latest

      - name: Logout from Docker Hub
        run: docker logout
